name: ecommerce
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dartz: ^0.10.1
  dio: ^5.2.1+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  get_it: ^7.6.0
  go_router: ^8.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  lottie: ^2.4.0
  modal_progress_hud_nsn: ^0.4.0
  photo_view: ^0.14.0
  print_color: ^3.0.5
  reactive_forms: ^15.0.0
  shared_preferences: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: null
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/lottie/

  fonts:
    - family: Metro
      fonts:
        - asset: assets/fonts/metro/metropolis.regular.otf
        - asset: assets/fonts/metro/metropolis.light.otf
          weight: 200
        - asset: assets/fonts/metro/metropolis.medium.otf
          weight: 400
        - asset: assets/fonts/metro/metropolis.semi-bold.otf
          weight: 500
        - asset: assets/fonts/metro/metropolis.bold.otf
          weight: 600
        - asset: assets/fonts/metro/metropolis.black.otf
          weight: 700

    - family: Tajawal
      fonts:
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
        - asset: assets/fonts/tajawal/Tajawal-Light.ttf
          weight: 200
        - asset: assets/fonts/tajawal/Tajawal-Regular.ttf
          weight: 400
        - asset: assets/fonts/tajawal/Tajawal-Medium.ttf
          weight: 500
        - asset: assets/fonts/tajawal/Tajawal-Bold.ttf
          weight: 600
        - asset: assets/fonts/tajawal/Tajawal-ExtraBold.ttf
          weight: 700

flutter_gen:
  output: lib/assets/

  integrations:
    flutter_svg: true
    lottie: true
    # flare_flutter: true
    # rive: true

flutter_native_splash:
  image: "assets/icons/logo.png"
  color: "#19A7CE"
  android: true
  ios: true
  web: false
  android_12:
    image: "assets/icons/logo-12.png"
