import 'package:hive/hive.dart';

part 'cart_product_model.g.dart'; // This file will be generated by Hive

@HiveType(typeId: 0)
class CartProductModel extends HiveObject {
  @HiveField(0)
  String productId;

  @HiveField(1)
  String title;

  @HiveField(2)
  String brand;

  @HiveField(3)
  double price;

  @HiveField(4)
  double priceBefore;

  @HiveField(5)
  double discountPercentage;

  @HiveField(6)
  int stock;

  @HiveField(7)
  String image;

  @HiveField(8)
  String description;

  @HiveField(9)
  int qty;

  CartProductModel({
    required this.productId,
    required this.title,
    required this.brand,
    required this.price,
    required this.priceBefore,
    required this.discountPercentage,
    required this.stock,
    required this.image,
    required this.description,
    required this.qty,
  });

  factory CartProductModel.fromJson(Map<String, dynamic> json) {
    return CartProductModel(
      productId: json['id'],
      title: json['title'],
      brand: json['brand'],
      price: json['price'],
      priceBefore: json['priceBefore'],
      discountPercentage: json['discountPercentage'],
      stock: json['stock'],
      description: json['description'],
      image: json['image'],
      qty: json['qty'],
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'productId': productId,
      'title': title,
      'brand': brand,
      'price': price,
      'priceBefore': priceBefore,
      'discountPercentage': discountPercentage,
      'stock': stock,
      'image': image,
      'description': description,
      'qty': qty,
    };
  }
}
